#!/bin/sh
echo "[post-rewrite hook: $1]"

# quick script to call "git submodule update" automatically if the
# .gitmodules file is changed

changedfiles=`git diff-tree --no-commit-id --name-only HEAD@{1} HEAD`

echo $changedfiles
if [ "${changedfiles[*]}" = "externals" ]; then
    echo "initializing & updating submodule(s)"
    git submodule update --init --recursive
fi
